apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: notification-svc
spec:
  ports:
  - port: 8040
    protocol: TCP
    targetPort: 8040
  selector:
    app: notification
  type: NodePort
status:
  loadBalancer: {}