apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  labels:
    app: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - name: maildev
        # Todo: Use stable
        image: maildev/maildev
        args: ["-s", "1025", "-w", "1080"]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maildev
  name: maildev-svc
spec:
  selector:
    app: maildev
  type: NodePort
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080