apiVersion: v1
kind: Service
metadata:
  labels:
    run: adminer
  name: adminer
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
    nodePort: 30090
  selector:
    run: adminer
  type: NodePort