apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: confi-server-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: NodePort
status:
  loadBalancer: {}
