apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-svc
spec:
  ports:
  - port: 8222
    protocol: TCP
    targetPort: 8222
  selector:
    app: gateway
  type: NodePort
status:
  loadBalancer: {}