apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-svc
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: product
  type: NodePort
status:
  loadBalancer: {}