apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: adama93/payment-service:latest
        name: payment
        ports:
          - containerPort: 8060
         
          

