apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer-svc
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: customer
  type: NodePort
status:
  loadBalancer: {}
