apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: adama93/customer:latest
        name: customer
        ports:
          - containerPort: 8090
         
          

