apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order-svc
spec:
  ports:
  - port: 8070
    protocol: TCP
    targetPort: 8070
  selector:
    app: order
  type: NodePort
status:
  loadBalancer: {}