apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 32001
  selector:
    app: mongo-express
  type: NodePort
status:
  loadBalancer: {}