apiVersion: v1
kind: Service
metadata:
  labels:
    run: keycloak
  name: keycloak
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30094
  selector:
    app: keycloak
  type: NodePort